const ACCESS_TOKEN =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4ZjQyMDk2NC1lZGJmLTQ0ZTYtYWMwYi0wOTZjNTliZGYyZGIiLCJyb2xlIjpbInRlYWNoZXIiXSwibGFzdE5hbWUiOiJNaW5oIiwiZmlyc3ROYW1lIjoiS2hhbmgiLCJlbWFpbCI6ImtoYW5oQGV4YW1wbGUuY29tIiwiaWF0IjoxNzQzNDk2MjcyLCJleHAiOjE3NDM1ODI2NzJ9.Y-us3YobP1hhZbnLUzD5BG4dmEGKSCLGQnDdHkz48-E'
const REFRESH_TOKEN = 'refresh_token'

const AUTH_ACTION_KEY = {
  SET_NOT_AUTH: 'SET_NOT_AUTH',
  SET_AUTHEN: 'SET_AUTHEN'
}

export { ACCESS_TOKEN, AUTH_ACTION_KEY, REFRESH_TOKEN }
